package github.lackxu.backend.entity;

import java.io.Serializable;
import lombok.Data;

/**
 * @TableName about
 */
@Data
public class About implements Serializable {
    /**
     * 
     *
     * @mbg.generated Wed Jan 13 12:40:29 CST 2021
     */
    private Integer id;

    /**
     * 
     *
     * @mbg.generated Wed Jan 13 12:40:29 CST 2021
     */
    private String context;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table about
     *
     * @mbg.generated Wed Jan 13 12:40:29 CST 2021
     */
    private static final long serialVersionUID = 1L;
}
