package entity;

import java.io.Serializable;
import lombok.Data;

/**
 * @TableName book
 */
@Data
public class Book implements Serializable {
    /**
     * 
     *
     * @mbg.generated Wed Jan 13 12:52:27 CST 2021
     */
    private Integer id;

    /**
     * 
     *
     * @mbg.generated Wed Jan 13 12:52:27 CST 2021
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book
     *
     * @mbg.generated Wed Jan 13 12:52:27 CST 2021
     */
    private static final long serialVersionUID = 1L;
}