package github.lackxu.noteman.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * @TableName note
 */
@Entity
@Data
public class Note implements Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * 
     *
     * @mbg.generated Wed Jan 13 15:21:40 CST 2021
     */
    private Long userId;

    /**
     * 
     *
     * @mbg.generated Wed Jan 13 15:21:40 CST 2021
     */
    private String title;

    /**
     * 
     *
     * @mbg.generated Wed Jan 13 15:21:40 CST 2021
     */
    private String description;

    /**
     * 
     *
     * @mbg.generated Wed Jan 13 15:21:40 CST 2021
     */
    private String context;

    /**
     * 
     *
     * @mbg.generated Wed Jan 13 15:21:40 CST 2021
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table note
     *
     * @mbg.generated Wed Jan 13 15:21:40 CST 2021
     */
    private static final long serialVersionUID = 1L;
}