package github.lackxu.noteman.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * @TableName todo
 */
@Data
public class Todo implements Serializable {
    /**
     * 
     *
     * @mbg.generated Thu Jan 14 16:50:02 CST 2021
     */
    private Integer id;

    /**
     * 
     *
     * @mbg.generated Thu Jan 14 16:50:02 CST 2021
     */
    private String context;

    /**
     * 
     *
     * @mbg.generated Thu Jan 14 16:50:02 CST 2021
     */
    private Date created;

    /**
     * 
     *
     * @mbg.generated Thu Jan 14 16:50:02 CST 2021
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table todo
     *
     * @mbg.generated Thu Jan 14 16:50:02 CST 2021
     */
    private static final long serialVersionUID = 1L;
}