package github.lackxu.noteman.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * @TableName user
 */
@Data
public class User implements Serializable {
    /**
     * 
     *
     * @mbg.generated Wed Jan 13 15:20:45 CST 2021
     */
    private Integer id;

    /**
     * 
     *
     * @mbg.generated Wed Jan 13 15:20:45 CST 2021
     */
    private String username;

    /**
     * 
     *
     * @mbg.generated Wed Jan 13 15:20:45 CST 2021
     */
    private String avatar;

    /**
     * 
     *
     * @mbg.generated Wed Jan 13 15:20:45 CST 2021
     */
    private String email;

    /**
     * 
     *
     * @mbg.generated Wed Jan 13 15:20:45 CST 2021
     */
    private String password;

    /**
     * 
     *
     * @mbg.generated Wed Jan 13 15:20:45 CST 2021
     */
    private Integer status;

    /**
     * 
     *
     * @mbg.generated Wed Jan 13 15:20:45 CST 2021
     */
    private Date created;

    /**
     * 
     *
     * @mbg.generated Wed Jan 13 15:20:45 CST 2021
     */
    private Date lastLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Wed Jan 13 15:20:45 CST 2021
     */
    private static final long serialVersionUID = 1L;
}